INSERT INTO locales_gossip_menu_option(menu_id,id,option_text_loc4) VALUES(2849,11,'专业训练师');
INSERT INTO locales_gossip_menu_option(menu_id,id,option_text_loc4) VALUES(2849,10,'职业训练师');
INSERT INTO locales_gossip_menu_option(menu_id,id,option_text_loc4) VALUES(2121,10,'职业训练师');
INSERT INTO locales_gossip_menu_option(menu_id,id,option_text_loc4) VALUES(1951,11,'职业训练师');
INSERT INTO locales_gossip_menu_option(menu_id,id,option_text_loc4) VALUES(435,13,'专业训练师');
INSERT INTO locales_gossip_menu_option(menu_id,id,option_text_loc4) VALUES(435,12,'职业训练师');
UPDATE locales_gossip_menu_option SET option_text_loc4='我能在旅馆里做些什么?' WHERE menu_id=344 AND id=3;;
UPDATE locales_gossip_menu_option SET option_text_loc4='把这旅店设为你的家' WHERE menu_id=344 AND id=2;;
UPDATE locales_gossip_menu_option SET option_text_loc4='我能在旅馆里做些什么?' WHERE menu_id=6769 AND id=0;;
UPDATE locales_gossip_menu_option SET option_text_loc4='我能在旅馆里做些什么?' WHERE menu_id=5181 AND id=0;;
UPDATE locales_gossip_menu_option SET option_text_loc4='我能在旅馆里做些什么?' WHERE menu_id=6768 AND id=0;;
